name: CI

on: [push, pull_request]

env:
  DEFAULT_PYTHON: 3.9

jobs:
  black:
    name: Check black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: psf/black@23.3.0
        with:
          options: "--check"
          src: "."

  isort:
    name: Check isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: jamescurtin/isort-action@master

  flake8:
    name: Check flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: TrueBrain/actions-flake8@master

  pylint:
    name: Check pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Run Pylint
        run: pylint sma-em-dev

  mypy:
    name: Check mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Run mypy
        continue-on-error: true
        run: |
          mypy --install-types --non-interactive sma-em-dev/
